

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int gyroVal = 0;

void spin(int power, int degree)
{
	SensorValue[Gyro] = 0;
	if (degree < 0)
	{
		while(abs(SensorValue[Gyro]) < abs(degree * 10))
		{
			gyroVal = SensorValue[Gyro];
			motor[leftWheel] = power;
			motor[rightWheel] = -power;
		}
	}
	else
	{
		while(abs(SensorValue[Gyro]) < abs(degree * 10))
		{
			gyroVal = SensorValue[Gyro];
			motor[leftWheel] = -power;
			motor[rightWheel] = power;
		}
	}
}
//void spinTest()
//{
//	spin(50,90);
//	halt();
//	wait10Msec(500);
//}
//task main()
//{
//	SensorValue[Gyro] = 0;
//	while(true)
//	{
//		spinTest();
//	gyroVal = SensorValue[Gyro];
//	}
//}
