#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, in2,    Potent,         sensorPotentiometer)
#pragma config(Sensor, dgtl5,  LimL1,          sensorTouch)
#pragma config(Sensor, dgtl6,  LimR1,          sensorTouch)
#pragma config(Sensor, dgtl11, stackEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl9, REnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl7, LEnc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           CMot,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LMots1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LMots2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LMots3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           MobMots1,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RMots1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RMots2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RMots3,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           MobMots2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LiftMot,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Ports 2-4 right drive motors (port 2 is y cabled)
//Ports 6-8 left drive motors (Ports 6 is y cabled)
//Ports 5 & 9 chain bar lift
//code is changeare goal lift motors
//Port 1 is claw motor
//Port 10 is the lift after new rewiring
//power expander on ports 4 & 5 & 8 & 9
int n = 1;
#define press = 1;
#define unpress = 0;
#include "DriveControls.h"
int gyroThing = 0;

task main() //Boff
{
	SensorType[Gyro] = sensorNone;
	gyroThing = SensorValue[Gyro];
 wait1Msec(100);
 //Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
 SensorType[Gyro] = sensorGyro;
 wait1Msec(2000);

//Adjust SensorScale to correct the scaling for your gyro
 SensorScale[in1] = 260;
 //Adjust SensorFullCount to set the "rollover" point. 3600 sets the rollover point to +/-3600
 SensorFullCount[in1] = 3600;

  SetupSens();
  setupController();
  while (true)
  {
  	if (vexRT[Btn7U] == 1)
		{
			n = n * -1;
		}
	gyroThing = SensorValue[Gyro];
  runController();


  }
}
