#pragma config(Motor,  port2,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	 motor[rightWheel]= 127;
	 motor[leftWheel] = 127;
	 wait10Msec(150);
	 motor[rightWheel] = 0;
	 motor[leftWheel] = 0;
	 motor[rightWheel] = -127;
	 motor[leftWheel] = -127;
	 wait10Msec(150);



}
