#pragma config(Motor,  port4,           test1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           test2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           test3,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           test4,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
{
if (abs(vexRT[Ch2]) > 20)

{
	motor[test1] = vexRT[Ch2];
	motor[test2] = vexRT[Ch2];
	motor[test3] = vexRT[Ch2];
	motor[test4] = vexRT[Ch2];
}
else
{
	motor[test1] = 0;
	motor[test2] = 0;
	motor[test3] = 0;
	motor[test4] = 0;
}
}
}
