#pragma config(Sensor, dgtl1,  Encode,         sensorQuadEncoder)
#pragma config(Motor,  port2,           Mot,           tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void Thing(int degrees,)
{
		int current = (SensorValue[Encode]) % 360;
		int currAbs = abs(current);
		int power = degrees - current;

		if (current != degrees)
		{
				if(current > degrees)
				{
						motor[Mot] = -power;
				}
				else if (current < degrees)
				{
					motor[Mot] = -power;
				}
				else
				{
					motor[Mot] = 0;
				}
		}
}
task main()
{
	SensorValue[Encode] = 0;
	while(true)
	{
		Thing(30);
	}
}
