#pragma config(Motor,  port2,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           left,          tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
	{
		if(vexRT[Ch2] > 10 || vexRT[Ch2] < -10)
		{
			 motor(right) = vexRT[Ch2];
		}
		else
		{
			 motor[right] = 0 ;
		}
		if(vexRT[Ch3]>10 || vexRT[Ch3]<-10)
		{
			 motor(left) = vexRT[Ch3];
		}
		else
	{
		motor[left] = 0 ;
		}
	}

}
