#pragma config(Motor,  port1,           Mot1,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Mot2,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           Mot3,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port4,           Mot4,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port5,           Mot5,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           Mot6,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port7,           Mot7,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port8,           Mot8,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port9,           Mot9,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,           Mot10,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
