
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!
#include "mainfile.c"
#include "autocode.h"

//void spinTest()
//{
//	spin(50,90);
//	halt();
//	wait10Msec(500);
//}



void turn(int power, int degree);
{
	SensorValue[Gyro] = 0;
	if (degree < 0)
	{
		while(abs(SensorValue[Gyro]) < abs(degree * 10))
		{
			gyroVal = SensorValue[Gyro];
			motor[left1] = power;
			motor[right1] = -power;
		}
	}
	else
	{
		while(abs(SensorValue[Gyro]) < abs(degree * 10))
		{
			gyroVal = SensorValue[Gyro];
			motor[left1] = -power;
			motor[right1] = power;
		}
	}
}
