#pragma config(Sensor, dgtl1,  Encode,         sensorQuadEncoder)
#pragma config(Motor,  port2,           Mot,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void Rotate(int target, float weight, int tolerance)
{
		int current = SensorValue[Encode];
		current = 0;
		int error = target - current;
		while (true)
		{
			current = SensorValue[Encode];
			error = target - current;
			if(abs(error * weight) < 15)
			{
				if(error >tolerance)
				{
					if(error < 0)
					{
						motor[Mot] = -15;
					}
					else
					{
						motor[Mot] = 15;
					}
				}
				else
				{
					motor[Mot] = 0;
				}
			}
			else
			{
				motor[Mot] = error * weight;
			}
			wait1Msec(25);
		}
}
task main()
{
	while(true)
		{
				Rotate(150,2,2);
		}

}
