#pragma config(Sensor, dgtl1,  REnc,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LEnc,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  flyEnc,         sensorQuadEncoder)
#pragma config(Motor,  port1,           left1,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left3,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           flyTop,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           flyMiddle,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           flyBottom,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           right1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          right3,        tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "AutonComms.h"
#include "MathFuncs.h"
#include "driveCode.h"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	runAuton();
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  //AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You m
ust modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task runDrive()
{
	drive();
}
task flywheel()
{
	readFlyWheel();
}

task usercontrol()
{
	SensorValue[REnc] = 0;
	SensorValue[flyEnc] = 0;
  // User control code here, inside the loop

 	startTask(runDrive);
 	startTask(flywheel);
}
