#pragma config(Motor,  port1,           Motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          Motor2,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[Motor1] = 127;
	motor[Motor2] = 127; //go
	wait1Msec(3000);
	motor[Motor1] = 0;
	motor[Motor2] = 80;
	wait1Msec(3000);
	motor[Motor1]=0;
	motor[motor[Motor2]
	motor[Motor1] = 0;
	motor[Motor2] = 0; //stop

}
